### ISSUE TITLE
Tailscale SSH Permissions

### ISSUE THREAD

**Issue by enjewneer** [classabbyamp/mkinitcpio-tailscale#2]
Whenever I try to connect to Tailscale SSH in ZFSBootMenu I get:

```
failed to look up enjewneer
enjewneer@servergoose-mkinitcpio: Permission denied (tailscale).
```

I've built ZFSBootMenu to include Tailscale and enabled ssh. I can see the machine online with ssh enabled from my Admin Console. Followed the instructions between your blog post, the README, and the ZFSBootMenu docs and set ACLs accordingly, using the tag "zfsbootmenu" for the mkinitcpio machine. I've also set ssh rules to allow all default and from src of tag:local to dst of tag:zfsbootmenu.

Troubleshooting steps I've tried:

- Tried ssh'ing as root
- After booting, I can ssh to the same host machine (with the -mkinitcpio) even if I set its tag to zfsbootmenu, so I don't believe it's an issue with ACLs/permissions
- I've also forced reauthorization of all my machines to temporarily completely remove ACL tags from machines. Again, this fails with the same error when trying to ssh into ZBM but works fine once booted to Void Linux

**Comment by classabbyamp** [comment]
I don't personally use tailscale ssh (i find the dropbear setup better), but the initramfs won't have any users other than root. you may need to do some tailscale ssh config to allow root login, i don't know

**Comment by enjewneer** [comment]
This is working now. I think it's possible that I had some other issues communicating to the machine at all over tailscale ssh. Now when logging in as root over ssh, it works.
